controller:
  image:
    registry: harbor.jamezrin.com
    repository: library/jenkins
    tag: latest
    pullPolicy: Always
  
  imagePullSecretName: personal-registry
  
  installPlugins: false

  ingress:
    enabled: true
    paths: []
    apiVersion: 'networking.k8s.io/v1'
    labels: {}
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      traefik.ingress.kubernetes.io/router.tls: 'true'
    hostName: jenkins.jamezrin.com
    tls:
      - secretName: jenkins.cluster.local
        hosts:
          - jenkins.jamezrin.com
  prometheus:
    enabled: true
